### ISSUE TITLE
Alliance Pings - Auth Error

### ISSUE THREAD

**Issue by ghost** [bravecollective/core#212] opened 2014-05-23 14:34 UTC
Found this trying to authorize alliance pings.

Request Data URL: string(41) "https://core.braveineve.com/api/core/info" HEADERS: array(3) { ["Date"]=> string(29) "Fri, 23 May 2014 14:32:38 GMT" ["X-Service"]=> string(24) "5351b367bce1931767f7443a" ["X-Signature"]=> string(127) "b2f49005ab428b887285954d9cd1f691b46d6b9c9037510f39141479f365aa3425d991ac28fc60debe52e49aa66cb5f2fb510d993b8f20a089167634f6abfac" } DATA: array(1) { ["token"]=> string(24) "537f5c05bce1932648960cc7" } Response Data: object(Requests_Response)#173 (9) { ["body"]=> string(290) "
Server Error

An error occurred. See the error logs for more information. (Turn debug on to display exception reports here) " ["raw"]=> string(468) "HTTP/1.1 500 Internal Server Error Server: openresty Date: Fri, 23 May 2014 14:32:38 GMT Content-Type: text/html; charset=utf8 Content-Length: 290 Connection: keep-alive
Server Error

An error occurred. See the error logs for more information. (Turn debug on to display exception reports here) " ["headers"]=> object(Requests_Response_Headers)#172 (1) { ["data":protected]=> array(4) { ["server"]=> array(1) { [0]=> string(9) "openresty" } ["date"]=> array(1) { [0]=> string(29) "Fri, 23 May 2014 14:32:38 GMT" } ["content-type"]=> array(1) { [0]=> string(23) "text/html; charset=utf8" } ["content-length"]=> array(1) { [0]=> string(3) "290" } } } ["status_code"]=> int(500) ["success"]=> bool(false) ["redirects"]=> int(0) ["url"]=> string(41) "https://core.braveineve.com/api/core/info" ["history"]=> array(0) { } ["cookies"]=> object(Requests_Cookie_Jar)#167 (1) { ["cookies":protected]=> array(0) { } } } Request Failed Credentials: array(1) { ["token"]=> string(24) "537f5c05bce1932648960cc7" }

**Comment by jboning** [comment] 2014-05-24 17:44
I vaguely suspect this is the same as #70. @Acidity, can you confirm/deny based on server logs?

**Comment by Acidity** [comment] 2014-05-24 18:29
It might be the same root cause, but typically #70 causes errors client on the client side rather than in core. 

```
"Fri, 23 May 2014 14:32:38 GMT
https://core.braveineve.com/api/core/info
token=REDACTED"
Error - <type 'exceptions.TypeError'>: Odd-length string
URL: https://core.braveineve.com/api/core/info
File '/home/core/local/lib/python2.7/site-packages/WebError-0.10.3-py2.7.egg/weberror/errormiddleware.py', line 162 in __call__
  app_iter = self.application(environ, sr_checker)
File '/home/core/local/lib/python2.7/site-packages/Beaker-1.6.4-py2.7.egg/beaker/middleware.py', line 73 in __call__
  return self.app(environ, start_response)
File '/home/core/local/lib/python2.7/site-packages/Paste-1.7.5.1-py2.7.egg/paste/registry.py', line 379 in __call__
  app_iter = self.application(environ, start_response)
File '/home/core/local/lib/python2.7/site-packages/Paste-1.7.5.1-py2.7.egg/paste/config.py', line 105 in register_config
  app_iter = application(environ, start_response)
File '/home/core/local/lib/python2.7/site-packages/Beaker-1.6.4-py2.7.egg/beaker/middleware.py', line 155 in __call__
  return self.wrap_app(environ, session_start_response)
File '/home/core/local/lib/python2.7/site-packages/WebCore-1.1.2-py2.7.egg/web/core/locale.py', line 242 in __call__
  return self.application(environ, start_response)
File '/home/core/local/lib/python2.7/site-packages/WebCore-1.1.2-py2.7.egg/web/auth/middleware.py', line 103 in __call__
  result = self.application(environ, our_start_response)
File '/home/core/local/lib/python2.7/site-packages/WebCore-1.1.2-py2.7.egg/web/core/templating.py', line 84 in __call__
  result = self.application(environ, start_response)
File '/home/core/local/lib/python2.7/site-packages/WebCore-1.1.2-py2.7.egg/web/core/application.py', line 151 in __call__
  content = self.root(web.core.request._current_obj())
File '/home/core/local/lib/python2.7/site-packages/WebCore-1.1.2-py2.7.egg/web/core/dialects/core.py', line 91 in __call__
  remaining, data = last.__before__(*remaining[1:], **data)
File '/home/core/usr/src/api/brave/api/controller.py', line 42 in __before__
  unhexlify(request.headers['X-Signature']),
TypeError: Odd-length string
```

**Comment by jboning** [comment] 2014-05-24 18:33
Oy, bad input from the ping app?

**Comment by Acidity** [comment] 2014-05-24 18:34
It looks like there's something wrong with the signature, but not in the typical off-by-time error... I'll cross post this into the ping repo.

**Comment by Acidity** [comment] 2014-07-05 23:42
Should have been resolved by https://github.com/bravecollective/php-api/commit/83043ea52ed00f6d85f7bd2ff8d58c57838f9e2b

**Closed as completed by Acidity** 2014-07-05 23:42 UTC
