### ISSUE TITLE
Can't switch character and broken UI

### ISSUE THREAD

**Issue by kiu** [bravecollective/core#55] opened 2014-02-02 11:35 UTC
See http://imgur.com/TSLYKeO
- The char in the upper corner is my alt.
- The char list under  https://core.bravecollective.net/character/ is correct
- There is a star on the page which I was able to click once (cant deselect it anymore)
- I can't switch the character to my main
- Clicking on https://core.bravecollective.net/application/, it tells me that Mumble is successfully authorized. Even though the upper right corner tells me that i am on my non BRAVE alt, which of course isn't authorized.

**Comment by kiu** [comment] 2014-02-02 11:47
Partially related to https://github.com/bravecollective/core/issues/43

**Comment by BlackVoid** [comment] 2014-02-02 13:25
It's a duplicate of the one you made related.

**Comment by kiu** [comment] 2014-02-02 13:46
Its not a duplicate, this one also reports that the char in the upper corner is wrong and i am unable to switch it.

**Comment by amcgregor** [comment] 2014-02-02 16:44
The one in the upper corner is simply the currently selected default character.  This is a pure duplicate (can't properly select default character because star icons are misaligned).

Within one account you can have as many characters loaded via EVE API as you want, with the capability to authorize a different user for each application.  The trick is that only one character can be authorized at a time per application.  The character in the upper right is what the Authorize button defaults to.  You can still select a different character by clicking the up arrow on the Authorize button.

**Closed as completed by amcgregor** 2014-02-02 16:44 UTC

**Comment by ghost** [comment] 2014-02-02 17:02
Related: https://github.com/bravecollective/mumble/issues/5

Note here that selecting a character (or using the default) while authorizing the Mumble app, may not actually update the displayed character in the Mumble app. this was reported in Firefox. Try clearing cookies if the Mumble app reports a different character selected than the one you chose in the dropdown while authorizing the Mumble app.

**Comment by kiu** [comment] 2014-02-02 17:34
Oh. Thats confusing :)

It shows my alt in the upper right corner, but actually under the authorized apps the list of authorized apps belongs to my main. So the content in core services is per account and the chars make no difference?

**Comment by amcgregor** [comment] 2014-02-03 14:12
No, it's per service.  Each thing that asks you to authorize gets its own association with one of your characters; the one you select when authorizing.  For example I could be Draleth on Mumble, but Takirah Nosha on the Forums.  Because currently the services don't get notified when you de-authorize you'll need to ensure you log out and log back into the service when switching characters for it.
