### ISSUE TITLE
User names must be case-insensitive.

### ISSUE THREAD

**Issue by ghost** [bravecollective/core#40] opened 2013-12-20 15:54 UTC
If you login with a username/password at [`/account/authenticate`](http://localhost:8080/account/authenticate) the capitalization of the username must match that on the account. The username should match case insensitively, and should be automatically lower-cased at all entry points for user name data.

**Comment by Acidity** [comment] 2014-03-22 20:49
I'll have a go at resolving this.

**Closed as completed** 2014-03-24 16:33 UTC
Labels: ✔✔✔, authentication, support

**Comment by jboning** [comment] 2014-03-25 06:47
What's the motivation for case insensitivity?

**Comment by Acidity** [comment] 2014-03-25 14:07
Usernames and email addresses are typically case insensitive, and we were having a lot of support issues where people would forget the exact capitalization of the username that they signed up.

**Comment by jboning** [comment] 2014-03-25 17:29
Ugh. Case insensitivity is an abomination. I guess if it lightens the support load, then it's probably a win, though. And it seems that everyone else on the internet does it.

Did you know that case transformation behaviour changes between different unicode versions? Have fun upgrading python!!

**Comment by ghost** [comment] 2014-03-27 02:59
eve character names are also case insensitive

there's not much, if any? reason for a case similar username

**Comment by jboning** [comment] 2014-03-27 03:02
Yeah, it's probably fine. I've just seen firsthand (at work) some terrible consequences of case-insensitivity so I'm a bit allergic to the idea of using case insensitivity anywhere.

**Comment by jboning** [comment] 2014-04-08 11:24
I just deployed SOUND's instance up to the latest on develop, and had problems with backwards incompatibility due to the case sensitivity changes. (I haven't 100% confirmed that this was the issue, but it fits my observations.) This requires a database migration to convert all existing users to have lowercase.

**Comment by Acidity** [comment] 2014-04-08 14:56
That is correct. This patch does require the database administrator change all existing email and usernames in the database to lowercase (and resolve any potential conflicts that might arise in doing so).

**Comment by Tomok** [comment] 2014-04-08 15:01
The same will apply for the fix for #57 since that assumes lowercase e-mails. Sorry for not mentioning that in a commit message.

**Comment by amcgregor** [comment] 2014-04-08 21:02
Canonicalization of potentially unicode data is, certainly, an abomination unto the eyes of the FSM.  And yes, we had a user sign up with the name "nyao~~~~🐱" (emoji cat face), for real-real.

That is, however, one support case vs. the many others where users are too silly to be able to remember the case of their username… or the case of their e-mail address.

Besides, canonicalization of e-mail address components basically means lower-case anyway (at least for the domain part and the user part excluding + note.)  It's a tough problem.

**Comment by ghost** [comment] 2014-04-08 21:36
as OP, i feel I should contribute!
i don't like coercing existing usernames and only storing lowercase usernames.

here's an approach I recently took in an unrelated project using couchdb. I allowed arbitrary-case usernames, but prevented creation of similar-case names and allowed logging in with similar-case names.

background: in couchdb, you craft some javascript functions that define a set of 'views'. These functions iterate over each document in the database and 'emit' zero or more key/value pairs for that document.

When you query a view, you get an array of key/value pairs generated by the view function.

If you pass a set of keys to the view query, couchdb restricts the output to only show entries where the key matches. (If you don't pass it any keys, you just get every single entry.)

details: For account creation I enforced a regex of allowed characters (which included upper and lower case characters.)

To test username availability (e.g. creating user) and username equivalence (e.g. logging in), I used a couchdb view similar to:

```
function(doc){
  if(doc.type == 'user'){ emit(doc.username.toLowerCase(), doc) };
}
```

(When couchdb sees `emit(key, value)` it knows to generate a key/value pair for that document when the view is queried.)

At each point in my code where I needed to check existing usernames, I downcased the user's input, and then queried the view with `input.downcase` as the key.

So the above view function returns a set of key/values where the values are documents whose `.username` property is similar-case to the user's input.  My next step was to test whether the length of the returned array of view entries was 0 (for account creation) or 1 (for login) or more (duplicate similar cased accounts, oops!)

caveat: i havent used mongo at all yet so idk the feasibility here!
