### ISSUE TITLE
 BadSignatureError when autenticating for the forum

### ISSUE THREAD

**Issue by randoomed** [bravecollective/core#70] opened 2014-02-03 09:41 UTC
I got this error when I went to forums.bravecollective.net
logged in to my account
pressed authenticate 

when i press: "re-get this page" on the error screen the forum loads normally

stacktrace:
`URL: https://forums.bravecollective.net/authorized?token=52ef605c58b70071c8e47aa8
File '/home/forums/lib/python2.7/site-packages/weberror/evalexception.py', line 431 in respond
  app_iter = self.application(environ, detect_start_response)
File '/home/forums/lib/python2.7/site-packages/Beaker-1.6.4-py2.7.egg/beaker/middleware.py', line 73 in __call__
  return self.app(environ, start_response)
File '/home/forums/lib/python2.7/site-packages/paste/registry.py', line 379 in __call__
  app_iter = self.application(environ, start_response)
File '/home/forums/lib/python2.7/site-packages/paste/config.py', line 105 in register_config
  app_iter = application(environ, start_response)
File '/home/forums/lib/python2.7/site-packages/Beaker-1.6.4-py2.7.egg/beaker/middleware.py', line 155 in __call__
  return self.wrap_app(environ, session_start_response)
File '/home/forums/lib/python2.7/site-packages/web/core/locale.py', line 242 in __call__
  return self.application(environ, start_response)
File '/home/forums/lib/python2.7/site-packages/web/auth/middleware.py', line 103 in __call__
  result = self.application(environ, our_start_response)
File '/home/forums/lib/python2.7/site-packages/web/core/templating.py', line 84 in __call__
  result = self.application(environ, start_response)
File '/home/forums/lib/python2.7/site-packages/web/core/application.py', line 151 in __call__
  content = self.root(web.core.request._current_obj())
File '/home/forums/lib/python2.7/site-packages/web/core/dialects/core.py', line 92 in __call__
  return last.__after__(part(*remaining, **data))
File '/home/forums/src/brave/forums/auth/controller.py', line 38 in authorized
  authenticate(token)
File '/home/forums/lib/python2.7/site-packages/web/auth/__init__.py', line 35 in authenticate
  result = config.authenticate(identifier, password)
File '/home/forums/lib/python2.7/site-packages/web/auth/middleware.py', line 70 in lazy
  return getattr(obj, prop)(*args, **kw)
File '/home/forums/src/brave/forums/auth/model.py', line 53 in authenticate
  result = api.core.info(identifier)
File '/home/forums/usr/src/api/brave/api/client.py', line 78 in __call__
  auth = SignedAuth(self.identity, self.private, self.public)
File '/home/forums/lib/python2.7/site-packages/requests-1.1.0-py2.7.egg/requests/sessions.py', line 340 in post
  return self.request('POST', url, data=data, **kwargs)
File '/home/forums/lib/python2.7/site-packages/requests-1.1.0-py2.7.egg/requests/sessions.py', line 279 in request
  resp = self.send(prep, stream=stream, timeout=timeout, verify=verify, cert=cert, proxies=proxies)
File '/home/forums/lib/python2.7/site-packages/requests-1.1.0-py2.7.egg/requests/sessions.py', line 374 in send
  r = adapter.send(request, **kwargs)
File '/home/forums/lib/python2.7/site-packages/requests-1.1.0-py2.7.egg/requests/adapters.py', line 219 in send
  r = self.build_response(request, resp)
File '/home/forums/lib/python2.7/site-packages/requests-1.1.0-py2.7.egg/requests/adapters.py', line 113 in build_response
  response = dispatch_hook('response', req.hooks, response)
File '/home/forums/lib/python2.7/site-packages/requests-1.1.0-py2.7.egg/requests/hooks.py', line 39 in dispatch_hook
  _hook_data = hook(hook_data)
File '/home/forums/usr/src/api/brave/api/client.py', line 48 in validate
  self.public.verify(unhexlify(response.headers['X-Signature']), canon)
File 'build/bdist.linux-x86_64/egg/ecdsa/keys.py', line 99 in verify
File 'build/bdist.linux-x86_64/egg/ecdsa/keys.py', line 111 in verify_digest
BadSignatureError:`

**Comment by amcgregor** [comment] 2014-02-04 15:07
This is a known race condition and can generally be resolved by refreshing the browser window.  It is caused by the Date header being one second out-of-sync with what the application thinks it is signing, thus a bad signature.

**Closed as completed** 2021-09-03 14:57 UTC
Labels: ✘, authentication, api, bug
